# Generated by Django 4.0.4 on 2022-05-31 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('season', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtype', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('total_episodes', models.IntegerField()),
                ('status', models.CharField(choices=[('Em andamento', 'Em andamento'), ('Finalizado', 'Finalizado'), ('Pausado', 'Pausado'), ('Cancelado', 'Cancelado')], max_length=255)),
                ('official_thumbnail', models.CharField(max_length=255)),
                ('custom_thumbnail', models.CharField(max_length=255)),
                ('studio', models.CharField(max_length=255)),
                ('kitsu_link', models.CharField(max_length=255)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('season_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='season.season')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
