# Generated by Django 4.0.4 on 2022-05-31 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='id',
        ),
        migrations.AddField(
            model_name='anime',
            name='anime_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
