# Generated by Django 4.0.4 on 2022-05-31 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(choices=[('Não lançado', 'Não lançado'), ('Em andamento', 'Em andamento'), ('Finalizado', 'Finalizado'), ('Pausado', 'Pausado'), ('Cancelado', 'Cancelado')], max_length=255),
        ),
        migrations.AlterField(
            model_name='anime',
            name='subtype',
            field=models.CharField(choices=[('TV', 'TV'), ('OVA', 'OVA'), ('ONA', 'ONA'), ('Filme', 'Filme'), ('Outro', 'Outro')], max_length=255),
        ),
    ]
