# Generated by Django 4.0.4 on 2022-06-01 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0002_anime_release_date_alter_anime_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='season_id',
            new_name='season',
        ),
    ]
