# Generated by Django 4.0.4 on 2022-05-31 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0002_remove_anime_id_anime_anime_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='anime_id',
        ),
        migrations.AddField(
            model_name='anime',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
