# Generated by Django 4.0.4 on 2022-06-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='author',
            new_name='serialization',
        ),
        migrations.AddField(
            model_name='manga',
            name='total_chapters',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
