# Generated by Django 4.0.4 on 2022-06-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0002_alter_manga_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
